language: node_js

node_js:
- 'node'

cache:
  directories:
    - node_modules

# install: true

stages:
  # - install
  - test
  - build docs
  - name: deploy docs
    if: branch = master
  - name: release staging
    if: branch = staging
  - name: release production
    if: branch = master

jobs:
  include:
    # - stage: install
    #   env:
    #     - NAME=install
    #   script: npm i -g npm@latest && npm ci
    - stage: test
      env:
        - NAME=jest
      script: npm run test-ci:prod && npm run report-coverage
    - stage: test
      env:
        - NAME=tslint
      script: npm run lint-ts
    # - stage: test
    #   env:
    #     - NAME=stylelint
    #   script: npm run lint-less

    - stage: test
      env:
        - NAME=webpack-publish
      script: npm run webpack
    - stage: test
      env:
        - NAME=storybook
      script: npm run storybook-publish
    - stage: build docs
      env:
        - NAME=typedoc
      script: npm run typedoc-publish

    - stage: test
      script: npm run storybook-publish && npm run typedoc-publish
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: gh-site
        target_branch: gh-pages
        on:
          all-branches: true
          conditon: $TRAVIS_BRANCH =~ ^staging|master$

    - stage: release staging
      script: npx semantic-release -b staging
    - stage: release production
      script: npx semantic-release
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
