language: node_js
node_js: 
  - "8"

install:
  - yarn install

script: 
  - yarn run build-ts
  - yarn run test

deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
  script:  echo "Deploying package to npm."
  skip_cleanup: true
  on:
    branch: master