language: node_js
node_js:
- 'node'
cache:
  directories:
    - node_modules

install:
- npm install
script:
- npm run test-ci:prod

after_success:
- npm run report-coverage
- npm run storybook-publish
- npm run typedoc-publish
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GIT_API_KEY
    local_dir: gh-site
    target_branch: gh-pages
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true 
