language: node_js

node_js:
- 'node'

cache:
  directories:
    - node_modules

install: true

stages:
  - install
  - test
  - build docs
  - name: release staging
    if: branch = staging
  - name: release production
    if: branch = master

jobs:
  include:
      script: npm i -g npm@latest && npm ci
    - stage: test
      script: npm run test-ci:prod && npm run report-coverage
      env:
        - NAME=jest
    - script: npm run lint-ts
      env:
        - NAME=tslint
    - script: npm run lint-less
      env:
        - NAME=stylelint
    - stage: build docs
      script: npm run storybook-publish
      env:
        - NAME=storybook
    - script: npm run typedoc-publish
      env:
        - NAME=typedoc
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: gh-site
        target_branch: gh-pages
        # on:
        #   all_branches: true
        #   if: $TRAVIS_BRANCH =~ ^staging|master$
    - stage: release staging
      script: npx semantic-release -b staging
    - stage: release production
      script: npx semantic-release
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
