# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout_code:
    docker:
      - image: node:10-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  install_dependencies:
    docker:
      - image: node:10-alpine

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE-SHA1 }}
      - run: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  unit_tests:
    docker:
      - image: node:10-alpine
        environment:
          COVERALLS_SERVICE_NAME: CircleCI
          COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
          COVERALLS_SERVICE_JOB_ID: $CIRCLE_SHA1

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE-SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Execute Jest unit tests
          command: npm run test-ci:prod
      - run:
          name: Report test coverage to Coveralls
          command: npm run report-coverage

  lint_typescript:
    docker:
      - image: node:10-alpine

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE-SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run TSLint against sourcefiles
          command: npm run lint-ts
  
  build_webpack:
    docker:
      - image: node:10-alpine

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE-SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Test that the bundle builds correctly
          command: npm run webpack:prod

  build_storybook:
    docker:
      - image: node:10-alpine

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE-SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Test that storybook builds correctly
          command: npm run storybook-publish
      - save_cache:
          key: v1-storybook-

  build_typedoc:
    docker:
      - image: node:10-alpine

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE-SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Test that typedoc builds correctly
          command: npm run typedoc-publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - unit_tests:
          requires:
            - install_dependencies
      - lint_typescript:
          requires:
            - install_dependencies
      - build_webpack:
          requires: 
            - unit_tests
      - build_storybook:
          requires:
            - unit_tests
      - build_typedoc:
          requires:
            - unit_tests
